package emby

type systemConfigurationResponse struct {
	EnableUPnP                           bool     `json:"EnableUPnP"`
	PublicPort                           int      `json:"PublicPort"`
	PublicHttpsPort                      int      `json:"PublicHttpsPort"`
	HttpServerPortNumber                 int      `json:"HttpServerPortNumber"`
	HttpsPortNumber                      int      `json:"HttpsPortNumber"`
	EnableHttps                          bool     `json:"EnableHttps"`
	IsPortAuthorized                     bool     `json:"IsPortAuthorized"`
	AutoRunWebApp                        bool     `json:"AutoRunWebApp"`
	EnableRemoteAccess                   bool     `json:"EnableRemoteAccess"`
	LogAllQueryTimes                     bool     `json:"LogAllQueryTimes"`
	DisableOutgoingIPv6                  bool     `json:"DisableOutgoingIPv6"`
	EnableCaseSensitiveItemIds           bool     `json:"EnableCaseSensitiveItemIds"`
	MetadataCountryCode                  string   `json:"MetadataCountryCode"`
	SortRemoveWords                      []string `json:"SortRemoveWords"`
	LibraryMonitorDelaySeconds           int      `json:"LibraryMonitorDelaySeconds"`
	EnableDashboardResponseCaching       bool     `json:"EnableDashboardResponseCaching"`
	ImageSavingConvention                string   `json:"ImageSavingConvention"`
	EnableAutomaticRestart               bool     `json:"EnableAutomaticRestart"`
	PreferredDetectedRemoteAddressFamily string   `json:"PreferredDetectedRemoteAddressFamily"`
	UICulture                            string   `json:"UICulture"`
	RemoteClientBitrateLimit             int      `json:"RemoteClientBitrateLimit"`
	LocalNetworkSubnets                  []string `json:"LocalNetworkSubnets"`
	LocalNetworkAddresses                []string `json:"LocalNetworkAddresses"`
	EnableExternalContentInSuggestions   bool     `json:"EnableExternalContentInSuggestions"`
	RequireHttps                         bool     `json:"RequireHttps"`
	IsBehindProxy                        bool     `json:"IsBehindProxy"`
	RemoteIPFilter                       []string `json:"RemoteIPFilter"`
	IsRemoteIPFilterBlacklist            bool     `json:"IsRemoteIPFilterBlacklist"`
	ImageExtractionTimeoutMs             int      `json:"ImageExtractionTimeoutMs"`
	PathSubstitutions                    []string `json:"PathSubstitutions"`
	UninstalledPlugins                   []string `json:"UninstalledPlugins"`
	CollapseVideoFolders                 bool     `json:"CollapseVideoFolders"`
	EnableOriginalTrackTitles            bool     `json:"EnableOriginalTrackTitles"`
	VacuumDatabaseOnStartup              bool     `json:"VacuumDatabaseOnStartup"`
	SimultaneousStreamLimit              int      `json:"SimultaneousStreamLimit"`
	DatabaseCacheSizeMB                  int      `json:"DatabaseCacheSizeMB"`
	EnableSqLiteMmio                     bool     `json:"EnableSqLiteMmio"`
	PlaylistsUpgradedToM3U               bool     `json:"PlaylistsUpgradedToM3U"`
	ImageExtractorUpgraded1              bool     `json:"ImageExtractorUpgraded1"`
	EnablePeopleLetterSubFolders         bool     `json:"EnablePeopleLetterSubFolders"`
	OptimizeDatabaseOnShutdown           bool     `json:"OptimizeDatabaseOnShutdown"`
	DatabaseAnalysisLimit                int      `json:"DatabaseAnalysisLimit"`
	MaxLibraryDatabaseConnections        int      `json:"MaxLibraryDatabaseConnections"`
	MaxAuthDbConnections                 int      `json:"MaxAuthDbConnections"`
	MaxOtherDbConnections                int      `json:"MaxOtherDbConnections"`
	DisableAsyncIO                       bool     `json:"DisableAsyncIO"`
	MigratedToUserItemShares8            bool     `json:"MigratedToUserItemShares8"`
	MigratedLibraryOptionsToDb           bool     `json:"MigratedLibraryOptionsToDb"`
	AllowLegacyLocalNetworkPassword      bool     `json:"AllowLegacyLocalNetworkPassword"`
	EnableSavedMetadataForPeople         bool     `json:"EnableSavedMetadataForPeople"`
	TvChannelsRefreshed                  bool     `json:"TvChannelsRefreshed"`
	ProxyHeaderMode                      string   `json:"ProxyHeaderMode"`
	IsInMaintenanceMode                  bool     `json:"IsInMaintenanceMode"`
	EnableDebugLevelLogging              bool     `json:"EnableDebugLevelLogging"`
	EnableAutoUpdate                     bool     `json:"EnableAutoUpdate"`
	LogFileRetentionDays                 int      `json:"LogFileRetentionDays"`
	RunAtStartup                         bool     `json:"RunAtStartup"`
	IsStartupWizardCompleted             bool     `json:"IsStartupWizardCompleted"`
}
